// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: plugin/pkg/services/agentpools/azure/flexvm/agentpools.proto

package flexvm

import (
	api "github.com/Azure/aks-flex/plugin/api"
	kubeadm "github.com/Azure/aks-flex/plugin/pkg/services/agentpools/api/features/kubeadm"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AgentPool models a single cross-region Azure VM.
//
// Unlike the ubuntu2404vmss service which manages a Virtual Machine Scale Set,
// flexvm creates one Microsoft.Compute/virtualMachines per AgentPool. This is
// suitable for cross-region placement and matches Karpenter's per-NodeClaim
// resource lifecycle.
//
// The plugin process is assumed to authenticate via DefaultAzureCredential and
// hold Contributor on the target subscription / resource group / subnet.
type AgentPool struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Metadata *api.Metadata          `protobuf:"bytes,1,opt,name=metadata"`
	xxx_hidden_Spec     *AgentPoolSpec         `protobuf:"bytes,2,opt,name=spec"`
	xxx_hidden_Status   *AgentPoolStatus       `protobuf:"bytes,3,opt,name=status"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AgentPool) Reset() {
	*x = AgentPool{}
	mi := &file_plugin_pkg_services_agentpools_azure_flexvm_agentpools_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentPool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentPool) ProtoMessage() {}

func (x *AgentPool) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pkg_services_agentpools_azure_flexvm_agentpools_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AgentPool) GetMetadata() *api.Metadata {
	if x != nil {
		return x.xxx_hidden_Metadata
	}
	return nil
}

func (x *AgentPool) GetSpec() *AgentPoolSpec {
	if x != nil {
		return x.xxx_hidden_Spec
	}
	return nil
}

func (x *AgentPool) GetStatus() *AgentPoolStatus {
	if x != nil {
		return x.xxx_hidden_Status
	}
	return nil
}

func (x *AgentPool) SetMetadata(v *api.Metadata) {
	x.xxx_hidden_Metadata = v
}

func (x *AgentPool) SetSpec(v *AgentPoolSpec) {
	x.xxx_hidden_Spec = v
}

func (x *AgentPool) SetStatus(v *AgentPoolStatus) {
	x.xxx_hidden_Status = v
}

func (x *AgentPool) HasMetadata() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Metadata != nil
}

func (x *AgentPool) HasSpec() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Spec != nil
}

func (x *AgentPool) HasStatus() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Status != nil
}

func (x *AgentPool) ClearMetadata() {
	x.xxx_hidden_Metadata = nil
}

func (x *AgentPool) ClearSpec() {
	x.xxx_hidden_Spec = nil
}

func (x *AgentPool) ClearStatus() {
	x.xxx_hidden_Status = nil
}

type AgentPool_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Metadata *api.Metadata
	Spec     *AgentPoolSpec
	Status   *AgentPoolStatus
}

func (b0 AgentPool_builder) Build() *AgentPool {
	m0 := &AgentPool{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Metadata = b.Metadata
	x.xxx_hidden_Spec = b.Spec
	x.xxx_hidden_Status = b.Status
	return m0
}

type AgentPoolSpec struct {
	state                       protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_SubscriptionId   *string                `protobuf:"bytes,1,opt,name=subscription_id,json=subscriptionId"`
	xxx_hidden_ResourceGroup    *string                `protobuf:"bytes,2,opt,name=resource_group,json=resourceGroup"`
	xxx_hidden_Location         *string                `protobuf:"bytes,3,opt,name=location"`
	xxx_hidden_SubnetId         *string                `protobuf:"bytes,4,opt,name=subnet_id,json=subnetId"`
	xxx_hidden_VmSize           *string                `protobuf:"bytes,5,opt,name=vm_size,json=vmSize"`
	xxx_hidden_ImageReference   *ImageReference        `protobuf:"bytes,6,opt,name=image_reference,json=imageReference"`
	xxx_hidden_ImageId          *string                `protobuf:"bytes,7,opt,name=image_id,json=imageId"`
	xxx_hidden_SecurityType     *string                `protobuf:"bytes,8,opt,name=security_type,json=securityType"`
	xxx_hidden_OsDiskSizeGb     int32                  `protobuf:"varint,9,opt,name=os_disk_size_gb,json=osDiskSizeGb"`
	xxx_hidden_SshPublicKeys    []string               `protobuf:"bytes,10,rep,name=ssh_public_keys,json=sshPublicKeys"`
	xxx_hidden_AllocatePublicIp bool                   `protobuf:"varint,11,opt,name=allocate_public_ip,json=allocatePublicIp"`
	xxx_hidden_Tags             map[string]string      `protobuf:"bytes,12,rep,name=tags" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_Kubeadm          *kubeadm.Config        `protobuf:"bytes,13,opt,name=kubeadm"`
	XXX_raceDetectHookData      protoimpl.RaceDetectHookData
	XXX_presence                [1]uint32
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *AgentPoolSpec) Reset() {
	*x = AgentPoolSpec{}
	mi := &file_plugin_pkg_services_agentpools_azure_flexvm_agentpools_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentPoolSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentPoolSpec) ProtoMessage() {}

func (x *AgentPoolSpec) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pkg_services_agentpools_azure_flexvm_agentpools_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AgentPoolSpec) GetSubscriptionId() string {
	if x != nil {
		if x.xxx_hidden_SubscriptionId != nil {
			return *x.xxx_hidden_SubscriptionId
		}
		return ""
	}
	return ""
}

func (x *AgentPoolSpec) GetResourceGroup() string {
	if x != nil {
		if x.xxx_hidden_ResourceGroup != nil {
			return *x.xxx_hidden_ResourceGroup
		}
		return ""
	}
	return ""
}

func (x *AgentPoolSpec) GetLocation() string {
	if x != nil {
		if x.xxx_hidden_Location != nil {
			return *x.xxx_hidden_Location
		}
		return ""
	}
	return ""
}

func (x *AgentPoolSpec) GetSubnetId() string {
	if x != nil {
		if x.xxx_hidden_SubnetId != nil {
			return *x.xxx_hidden_SubnetId
		}
		return ""
	}
	return ""
}

func (x *AgentPoolSpec) GetVmSize() string {
	if x != nil {
		if x.xxx_hidden_VmSize != nil {
			return *x.xxx_hidden_VmSize
		}
		return ""
	}
	return ""
}

func (x *AgentPoolSpec) GetImageReference() *ImageReference {
	if x != nil {
		return x.xxx_hidden_ImageReference
	}
	return nil
}

func (x *AgentPoolSpec) GetImageId() string {
	if x != nil {
		if x.xxx_hidden_ImageId != nil {
			return *x.xxx_hidden_ImageId
		}
		return ""
	}
	return ""
}

func (x *AgentPoolSpec) GetSecurityType() string {
	if x != nil {
		if x.xxx_hidden_SecurityType != nil {
			return *x.xxx_hidden_SecurityType
		}
		return ""
	}
	return ""
}

func (x *AgentPoolSpec) GetOsDiskSizeGb() int32 {
	if x != nil {
		return x.xxx_hidden_OsDiskSizeGb
	}
	return 0
}

func (x *AgentPoolSpec) GetSshPublicKeys() []string {
	if x != nil {
		return x.xxx_hidden_SshPublicKeys
	}
	return nil
}

func (x *AgentPoolSpec) GetAllocatePublicIp() bool {
	if x != nil {
		return x.xxx_hidden_AllocatePublicIp
	}
	return false
}

func (x *AgentPoolSpec) GetTags() map[string]string {
	if x != nil {
		return x.xxx_hidden_Tags
	}
	return nil
}

func (x *AgentPoolSpec) GetKubeadm() *kubeadm.Config {
	if x != nil {
		return x.xxx_hidden_Kubeadm
	}
	return nil
}

func (x *AgentPoolSpec) SetSubscriptionId(v string) {
	x.xxx_hidden_SubscriptionId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 13)
}

func (x *AgentPoolSpec) SetResourceGroup(v string) {
	x.xxx_hidden_ResourceGroup = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 13)
}

func (x *AgentPoolSpec) SetLocation(v string) {
	x.xxx_hidden_Location = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 13)
}

func (x *AgentPoolSpec) SetSubnetId(v string) {
	x.xxx_hidden_SubnetId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 13)
}

func (x *AgentPoolSpec) SetVmSize(v string) {
	x.xxx_hidden_VmSize = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 13)
}

func (x *AgentPoolSpec) SetImageReference(v *ImageReference) {
	x.xxx_hidden_ImageReference = v
}

func (x *AgentPoolSpec) SetImageId(v string) {
	x.xxx_hidden_ImageId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 13)
}

func (x *AgentPoolSpec) SetSecurityType(v string) {
	x.xxx_hidden_SecurityType = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 7, 13)
}

func (x *AgentPoolSpec) SetOsDiskSizeGb(v int32) {
	x.xxx_hidden_OsDiskSizeGb = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 8, 13)
}

func (x *AgentPoolSpec) SetSshPublicKeys(v []string) {
	x.xxx_hidden_SshPublicKeys = v
}

func (x *AgentPoolSpec) SetAllocatePublicIp(v bool) {
	x.xxx_hidden_AllocatePublicIp = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 10, 13)
}

func (x *AgentPoolSpec) SetTags(v map[string]string) {
	x.xxx_hidden_Tags = v
}

func (x *AgentPoolSpec) SetKubeadm(v *kubeadm.Config) {
	x.xxx_hidden_Kubeadm = v
}

func (x *AgentPoolSpec) HasSubscriptionId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *AgentPoolSpec) HasResourceGroup() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *AgentPoolSpec) HasLocation() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *AgentPoolSpec) HasSubnetId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *AgentPoolSpec) HasVmSize() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *AgentPoolSpec) HasImageReference() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ImageReference != nil
}

func (x *AgentPoolSpec) HasImageId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *AgentPoolSpec) HasSecurityType() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 7)
}

func (x *AgentPoolSpec) HasOsDiskSizeGb() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 8)
}

func (x *AgentPoolSpec) HasAllocatePublicIp() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 10)
}

func (x *AgentPoolSpec) HasKubeadm() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Kubeadm != nil
}

func (x *AgentPoolSpec) ClearSubscriptionId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_SubscriptionId = nil
}

func (x *AgentPoolSpec) ClearResourceGroup() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_ResourceGroup = nil
}

func (x *AgentPoolSpec) ClearLocation() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Location = nil
}

func (x *AgentPoolSpec) ClearSubnetId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_SubnetId = nil
}

func (x *AgentPoolSpec) ClearVmSize() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_VmSize = nil
}

func (x *AgentPoolSpec) ClearImageReference() {
	x.xxx_hidden_ImageReference = nil
}

func (x *AgentPoolSpec) ClearImageId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_ImageId = nil
}

func (x *AgentPoolSpec) ClearSecurityType() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 7)
	x.xxx_hidden_SecurityType = nil
}

func (x *AgentPoolSpec) ClearOsDiskSizeGb() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 8)
	x.xxx_hidden_OsDiskSizeGb = 0
}

func (x *AgentPoolSpec) ClearAllocatePublicIp() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 10)
	x.xxx_hidden_AllocatePublicIp = false
}

func (x *AgentPoolSpec) ClearKubeadm() {
	x.xxx_hidden_Kubeadm = nil
}

type AgentPoolSpec_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	SubscriptionId *string
	ResourceGroup  *string
	Location       *string
	// Full ARM resource ID of the subnet (must already exist).
	SubnetId *string
	// VM SKU, e.g. "Standard_ND96isr_H200_v5".
	VmSize *string
	// ImageReference selects an Azure Marketplace image.
	// Mutually exclusive with image_id.
	ImageReference *ImageReference
	// SIG / community gallery image resource ID.
	// Mutually exclusive with image_reference.
	ImageId *string
	// Currently only "Standard" is supported. TrustedLaunch is deferred —
	// it has been observed to break the DSVM image during manual H200 bringup.
	SecurityType     *string
	OsDiskSizeGb     *int32
	SshPublicKeys    []string
	AllocatePublicIp *bool
	Tags             map[string]string
	Kubeadm          *kubeadm.Config
}

func (b0 AgentPoolSpec_builder) Build() *AgentPoolSpec {
	m0 := &AgentPoolSpec{}
	b, x := &b0, m0
	_, _ = b, x
	if b.SubscriptionId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 13)
		x.xxx_hidden_SubscriptionId = b.SubscriptionId
	}
	if b.ResourceGroup != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 13)
		x.xxx_hidden_ResourceGroup = b.ResourceGroup
	}
	if b.Location != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 13)
		x.xxx_hidden_Location = b.Location
	}
	if b.SubnetId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 13)
		x.xxx_hidden_SubnetId = b.SubnetId
	}
	if b.VmSize != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 13)
		x.xxx_hidden_VmSize = b.VmSize
	}
	x.xxx_hidden_ImageReference = b.ImageReference
	if b.ImageId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 13)
		x.xxx_hidden_ImageId = b.ImageId
	}
	if b.SecurityType != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 7, 13)
		x.xxx_hidden_SecurityType = b.SecurityType
	}
	if b.OsDiskSizeGb != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 8, 13)
		x.xxx_hidden_OsDiskSizeGb = *b.OsDiskSizeGb
	}
	x.xxx_hidden_SshPublicKeys = b.SshPublicKeys
	if b.AllocatePublicIp != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 10, 13)
		x.xxx_hidden_AllocatePublicIp = *b.AllocatePublicIp
	}
	x.xxx_hidden_Tags = b.Tags
	x.xxx_hidden_Kubeadm = b.Kubeadm
	return m0
}

type ImageReference struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Publisher   *string                `protobuf:"bytes,1,opt,name=publisher"`
	xxx_hidden_Offer       *string                `protobuf:"bytes,2,opt,name=offer"`
	xxx_hidden_Sku         *string                `protobuf:"bytes,3,opt,name=sku"`
	xxx_hidden_Version     *string                `protobuf:"bytes,4,opt,name=version"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ImageReference) Reset() {
	*x = ImageReference{}
	mi := &file_plugin_pkg_services_agentpools_azure_flexvm_agentpools_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageReference) ProtoMessage() {}

func (x *ImageReference) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pkg_services_agentpools_azure_flexvm_agentpools_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ImageReference) GetPublisher() string {
	if x != nil {
		if x.xxx_hidden_Publisher != nil {
			return *x.xxx_hidden_Publisher
		}
		return ""
	}
	return ""
}

func (x *ImageReference) GetOffer() string {
	if x != nil {
		if x.xxx_hidden_Offer != nil {
			return *x.xxx_hidden_Offer
		}
		return ""
	}
	return ""
}

func (x *ImageReference) GetSku() string {
	if x != nil {
		if x.xxx_hidden_Sku != nil {
			return *x.xxx_hidden_Sku
		}
		return ""
	}
	return ""
}

func (x *ImageReference) GetVersion() string {
	if x != nil {
		if x.xxx_hidden_Version != nil {
			return *x.xxx_hidden_Version
		}
		return ""
	}
	return ""
}

func (x *ImageReference) SetPublisher(v string) {
	x.xxx_hidden_Publisher = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *ImageReference) SetOffer(v string) {
	x.xxx_hidden_Offer = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *ImageReference) SetSku(v string) {
	x.xxx_hidden_Sku = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *ImageReference) SetVersion(v string) {
	x.xxx_hidden_Version = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *ImageReference) HasPublisher() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ImageReference) HasOffer() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ImageReference) HasSku() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *ImageReference) HasVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *ImageReference) ClearPublisher() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Publisher = nil
}

func (x *ImageReference) ClearOffer() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Offer = nil
}

func (x *ImageReference) ClearSku() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Sku = nil
}

func (x *ImageReference) ClearVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Version = nil
}

type ImageReference_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Publisher *string
	Offer     *string
	Sku       *string
	Version   *string
}

func (b0 ImageReference_builder) Build() *ImageReference {
	m0 := &ImageReference{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Publisher != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_Publisher = b.Publisher
	}
	if b.Offer != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_Offer = b.Offer
	}
	if b.Sku != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_Sku = b.Sku
	}
	if b.Version != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_Version = b.Version
	}
	return m0
}

type AgentPoolStatus struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_VmResourceId *string                `protobuf:"bytes,1,opt,name=vm_resource_id,json=vmResourceId"`
	xxx_hidden_CreatedAt    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt"`
	XXX_raceDetectHookData  protoimpl.RaceDetectHookData
	XXX_presence            [1]uint32
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *AgentPoolStatus) Reset() {
	*x = AgentPoolStatus{}
	mi := &file_plugin_pkg_services_agentpools_azure_flexvm_agentpools_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentPoolStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentPoolStatus) ProtoMessage() {}

func (x *AgentPoolStatus) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pkg_services_agentpools_azure_flexvm_agentpools_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AgentPoolStatus) GetVmResourceId() string {
	if x != nil {
		if x.xxx_hidden_VmResourceId != nil {
			return *x.xxx_hidden_VmResourceId
		}
		return ""
	}
	return ""
}

func (x *AgentPoolStatus) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_CreatedAt
	}
	return nil
}

func (x *AgentPoolStatus) SetVmResourceId(v string) {
	x.xxx_hidden_VmResourceId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *AgentPoolStatus) SetCreatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_CreatedAt = v
}

func (x *AgentPoolStatus) HasVmResourceId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *AgentPoolStatus) HasCreatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_CreatedAt != nil
}

func (x *AgentPoolStatus) ClearVmResourceId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_VmResourceId = nil
}

func (x *AgentPoolStatus) ClearCreatedAt() {
	x.xxx_hidden_CreatedAt = nil
}

type AgentPoolStatus_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Full ARM resource ID of the created VM.
	VmResourceId *string
	CreatedAt    *timestamppb.Timestamp
}

func (b0 AgentPoolStatus_builder) Build() *AgentPoolStatus {
	m0 := &AgentPoolStatus{}
	b, x := &b0, m0
	_, _ = b, x
	if b.VmResourceId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_VmResourceId = b.VmResourceId
	}
	x.xxx_hidden_CreatedAt = b.CreatedAt
	return m0
}

var File_plugin_pkg_services_agentpools_azure_flexvm_agentpools_proto protoreflect.FileDescriptor

const file_plugin_pkg_services_agentpools_azure_flexvm_agentpools_proto_rawDesc = "" +
	"\n" +
	"<plugin/pkg/services/agentpools/azure/flexvm/agentpools.proto\x12\x17agentpools.azure.flexvm\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x14plugin/api/api.proto\x1aAplugin/pkg/services/agentpools/api/features/kubeadm/kubeadm.proto\"\xb4\x01\n" +
	"\tAgentPool\x12)\n" +
	"\bmetadata\x18\x01 \x01(\v2\r.api.MetadataR\bmetadata\x12:\n" +
	"\x04spec\x18\x02 \x01(\v2&.agentpools.azure.flexvm.AgentPoolSpecR\x04spec\x12@\n" +
	"\x06status\x18\x03 \x01(\v2(.agentpools.azure.flexvm.AgentPoolStatusR\x06status\"\xea\x04\n" +
	"\rAgentPoolSpec\x12'\n" +
	"\x0fsubscription_id\x18\x01 \x01(\tR\x0esubscriptionId\x12%\n" +
	"\x0eresource_group\x18\x02 \x01(\tR\rresourceGroup\x12\x1a\n" +
	"\blocation\x18\x03 \x01(\tR\blocation\x12\x1b\n" +
	"\tsubnet_id\x18\x04 \x01(\tR\bsubnetId\x12\x17\n" +
	"\avm_size\x18\x05 \x01(\tR\x06vmSize\x12P\n" +
	"\x0fimage_reference\x18\x06 \x01(\v2'.agentpools.azure.flexvm.ImageReferenceR\x0eimageReference\x12\x19\n" +
	"\bimage_id\x18\a \x01(\tR\aimageId\x12#\n" +
	"\rsecurity_type\x18\b \x01(\tR\fsecurityType\x12%\n" +
	"\x0fos_disk_size_gb\x18\t \x01(\x05R\fosDiskSizeGb\x12&\n" +
	"\x0fssh_public_keys\x18\n" +
	" \x03(\tR\rsshPublicKeys\x12,\n" +
	"\x12allocate_public_ip\x18\v \x01(\bR\x10allocatePublicIp\x12D\n" +
	"\x04tags\x18\f \x03(\v20.agentpools.azure.flexvm.AgentPoolSpec.TagsEntryR\x04tags\x12)\n" +
	"\akubeadm\x18\r \x01(\v2\x0f.kubeadm.ConfigR\akubeadm\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"p\n" +
	"\x0eImageReference\x12\x1c\n" +
	"\tpublisher\x18\x01 \x01(\tR\tpublisher\x12\x14\n" +
	"\x05offer\x18\x02 \x01(\tR\x05offer\x12\x10\n" +
	"\x03sku\x18\x03 \x01(\tR\x03sku\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\"r\n" +
	"\x0fAgentPoolStatus\x12$\n" +
	"\x0evm_resource_id\x18\x01 \x01(\tR\fvmResourceId\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtBGZEgithub.com/Azure/aks-flex/plugin/pkg/services/agentpools/azure/flexvmb\beditionsp\xe9\a"

var file_plugin_pkg_services_agentpools_azure_flexvm_agentpools_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_plugin_pkg_services_agentpools_azure_flexvm_agentpools_proto_goTypes = []any{
	(*AgentPool)(nil),             // 0: agentpools.azure.flexvm.AgentPool
	(*AgentPoolSpec)(nil),         // 1: agentpools.azure.flexvm.AgentPoolSpec
	(*ImageReference)(nil),        // 2: agentpools.azure.flexvm.ImageReference
	(*AgentPoolStatus)(nil),       // 3: agentpools.azure.flexvm.AgentPoolStatus
	nil,                           // 4: agentpools.azure.flexvm.AgentPoolSpec.TagsEntry
	(*api.Metadata)(nil),          // 5: api.Metadata
	(*kubeadm.Config)(nil),        // 6: kubeadm.Config
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_plugin_pkg_services_agentpools_azure_flexvm_agentpools_proto_depIdxs = []int32{
	5, // 0: agentpools.azure.flexvm.AgentPool.metadata:type_name -> api.Metadata
	1, // 1: agentpools.azure.flexvm.AgentPool.spec:type_name -> agentpools.azure.flexvm.AgentPoolSpec
	3, // 2: agentpools.azure.flexvm.AgentPool.status:type_name -> agentpools.azure.flexvm.AgentPoolStatus
	2, // 3: agentpools.azure.flexvm.AgentPoolSpec.image_reference:type_name -> agentpools.azure.flexvm.ImageReference
	4, // 4: agentpools.azure.flexvm.AgentPoolSpec.tags:type_name -> agentpools.azure.flexvm.AgentPoolSpec.TagsEntry
	6, // 5: agentpools.azure.flexvm.AgentPoolSpec.kubeadm:type_name -> kubeadm.Config
	7, // 6: agentpools.azure.flexvm.AgentPoolStatus.created_at:type_name -> google.protobuf.Timestamp
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_plugin_pkg_services_agentpools_azure_flexvm_agentpools_proto_init() }
func file_plugin_pkg_services_agentpools_azure_flexvm_agentpools_proto_init() {
	if File_plugin_pkg_services_agentpools_azure_flexvm_agentpools_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_pkg_services_agentpools_azure_flexvm_agentpools_proto_rawDesc), len(file_plugin_pkg_services_agentpools_azure_flexvm_agentpools_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_plugin_pkg_services_agentpools_azure_flexvm_agentpools_proto_goTypes,
		DependencyIndexes: file_plugin_pkg_services_agentpools_azure_flexvm_agentpools_proto_depIdxs,
		MessageInfos:      file_plugin_pkg_services_agentpools_azure_flexvm_agentpools_proto_msgTypes,
	}.Build()
	File_plugin_pkg_services_agentpools_azure_flexvm_agentpools_proto = out.File
	file_plugin_pkg_services_agentpools_azure_flexvm_agentpools_proto_goTypes = nil
	file_plugin_pkg_services_agentpools_azure_flexvm_agentpools_proto_depIdxs = nil
}
