// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: plugin/pkg/services/agentpools/azure/flexvm/instances.proto

package flexvm

import (
	api "github.com/Azure/aks-flex/plugin/api"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// flexvm models one VM per AgentPool, so an Instance is just the AgentPool
// itself with id "<agentpool>/0". This matches the AWS ubuntu2404instance shape.
type Instance struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Metadata *api.Metadata          `protobuf:"bytes,1,opt,name=metadata"`
	xxx_hidden_Spec     *InstanceSpec          `protobuf:"bytes,2,opt,name=spec"`
	xxx_hidden_Status   *InstanceStatus        `protobuf:"bytes,3,opt,name=status"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Instance) Reset() {
	*x = Instance{}
	mi := &file_plugin_pkg_services_agentpools_azure_flexvm_instances_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Instance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Instance) ProtoMessage() {}

func (x *Instance) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pkg_services_agentpools_azure_flexvm_instances_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Instance) GetMetadata() *api.Metadata {
	if x != nil {
		return x.xxx_hidden_Metadata
	}
	return nil
}

func (x *Instance) GetSpec() *InstanceSpec {
	if x != nil {
		return x.xxx_hidden_Spec
	}
	return nil
}

func (x *Instance) GetStatus() *InstanceStatus {
	if x != nil {
		return x.xxx_hidden_Status
	}
	return nil
}

func (x *Instance) SetMetadata(v *api.Metadata) {
	x.xxx_hidden_Metadata = v
}

func (x *Instance) SetSpec(v *InstanceSpec) {
	x.xxx_hidden_Spec = v
}

func (x *Instance) SetStatus(v *InstanceStatus) {
	x.xxx_hidden_Status = v
}

func (x *Instance) HasMetadata() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Metadata != nil
}

func (x *Instance) HasSpec() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Spec != nil
}

func (x *Instance) HasStatus() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Status != nil
}

func (x *Instance) ClearMetadata() {
	x.xxx_hidden_Metadata = nil
}

func (x *Instance) ClearSpec() {
	x.xxx_hidden_Spec = nil
}

func (x *Instance) ClearStatus() {
	x.xxx_hidden_Status = nil
}

type Instance_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Metadata *api.Metadata
	Spec     *InstanceSpec
	Status   *InstanceStatus
}

func (b0 Instance_builder) Build() *Instance {
	m0 := &Instance{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Metadata = b.Metadata
	x.xxx_hidden_Spec = b.Spec
	x.xxx_hidden_Status = b.Status
	return m0
}

type InstanceSpec struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstanceSpec) Reset() {
	*x = InstanceSpec{}
	mi := &file_plugin_pkg_services_agentpools_azure_flexvm_instances_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstanceSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstanceSpec) ProtoMessage() {}

func (x *InstanceSpec) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pkg_services_agentpools_azure_flexvm_instances_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type InstanceSpec_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 InstanceSpec_builder) Build() *InstanceSpec {
	m0 := &InstanceSpec{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type InstanceStatus struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstanceStatus) Reset() {
	*x = InstanceStatus{}
	mi := &file_plugin_pkg_services_agentpools_azure_flexvm_instances_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstanceStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstanceStatus) ProtoMessage() {}

func (x *InstanceStatus) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pkg_services_agentpools_azure_flexvm_instances_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type InstanceStatus_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 InstanceStatus_builder) Build() *InstanceStatus {
	m0 := &InstanceStatus{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

var File_plugin_pkg_services_agentpools_azure_flexvm_instances_proto protoreflect.FileDescriptor

const file_plugin_pkg_services_agentpools_azure_flexvm_instances_proto_rawDesc = "" +
	"\n" +
	";plugin/pkg/services/agentpools/azure/flexvm/instances.proto\x12\x17agentpools.azure.flexvm\x1a\x14plugin/api/api.proto\"\xb1\x01\n" +
	"\bInstance\x12)\n" +
	"\bmetadata\x18\x01 \x01(\v2\r.api.MetadataR\bmetadata\x129\n" +
	"\x04spec\x18\x02 \x01(\v2%.agentpools.azure.flexvm.InstanceSpecR\x04spec\x12?\n" +
	"\x06status\x18\x03 \x01(\v2'.agentpools.azure.flexvm.InstanceStatusR\x06status\"\x0e\n" +
	"\fInstanceSpec\"\x10\n" +
	"\x0eInstanceStatusBGZEgithub.com/Azure/aks-flex/plugin/pkg/services/agentpools/azure/flexvmb\beditionsp\xe9\a"

var file_plugin_pkg_services_agentpools_azure_flexvm_instances_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_plugin_pkg_services_agentpools_azure_flexvm_instances_proto_goTypes = []any{
	(*Instance)(nil),       // 0: agentpools.azure.flexvm.Instance
	(*InstanceSpec)(nil),   // 1: agentpools.azure.flexvm.InstanceSpec
	(*InstanceStatus)(nil), // 2: agentpools.azure.flexvm.InstanceStatus
	(*api.Metadata)(nil),   // 3: api.Metadata
}
var file_plugin_pkg_services_agentpools_azure_flexvm_instances_proto_depIdxs = []int32{
	3, // 0: agentpools.azure.flexvm.Instance.metadata:type_name -> api.Metadata
	1, // 1: agentpools.azure.flexvm.Instance.spec:type_name -> agentpools.azure.flexvm.InstanceSpec
	2, // 2: agentpools.azure.flexvm.Instance.status:type_name -> agentpools.azure.flexvm.InstanceStatus
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_plugin_pkg_services_agentpools_azure_flexvm_instances_proto_init() }
func file_plugin_pkg_services_agentpools_azure_flexvm_instances_proto_init() {
	if File_plugin_pkg_services_agentpools_azure_flexvm_instances_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_pkg_services_agentpools_azure_flexvm_instances_proto_rawDesc), len(file_plugin_pkg_services_agentpools_azure_flexvm_instances_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_plugin_pkg_services_agentpools_azure_flexvm_instances_proto_goTypes,
		DependencyIndexes: file_plugin_pkg_services_agentpools_azure_flexvm_instances_proto_depIdxs,
		MessageInfos:      file_plugin_pkg_services_agentpools_azure_flexvm_instances_proto_msgTypes,
	}.Build()
	File_plugin_pkg_services_agentpools_azure_flexvm_instances_proto = out.File
	file_plugin_pkg_services_agentpools_azure_flexvm_instances_proto_goTypes = nil
	file_plugin_pkg_services_agentpools_azure_flexvm_instances_proto_depIdxs = nil
}
