package helper

import (
	"context"
	"fmt"
	"reflect"

	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/known/anypb"
)

// This package provides syntactic sugar functions that wrap the gRPC
// autogenerated clients which help code readability and brevity at point of
// use.

// id is an interface that implements SetId(string), and we also know the
// underlying type implementing the interface so that we can new() it.
type id[UNDERLYING any] interface {
	SetId(string)
	*UNDERLYING
}

type item interface {
	SetItem(*anypb.Any)
	GetItem() *anypb.Any
}

// item2 is an interface that implements the same method set as item, and we
// also know the underlying type implementing the interface so that we can new()
// it.
type item2[UNDERLYING any] interface {
	item
	*UNDERLYING
}

type items interface {
	SetItems([]*anypb.Any)
	GetItems() []*anypb.Any
}

func CreateOrUpdate[M proto.Message, REQT any, REQ item2[REQT], RESP item](createOrUpdate func(context.Context, REQ, ...grpc.CallOption) (RESP, error), ctx context.Context, m M, opts ...grpc.CallOption) (M, error) {
	item, err := anypb.New(m)
	if err != nil {
		return *new(M), err
	}

	req := REQ(new(REQT))
	req.SetItem(item)

	resp, err := createOrUpdate(ctx, req, opts...)
	if err != nil {
		return *new(M), err
	}

	return AnyTo[M](resp.GetItem())
}

func Delete[REQT any, REQ id[REQT], RESP any](delete_ func(context.Context, REQ, ...grpc.CallOption) (RESP, error), ctx context.Context, id string, opts ...grpc.CallOption) error {
	req := REQ(new(REQT))
	req.SetId(id)

	_, err := delete_(ctx, req, opts...)
	return err
}

func Get[M proto.Message, REQT any, REQ id[REQT], RESP item](get func(context.Context, REQ, ...grpc.CallOption) (RESP, error), ctx context.Context, id string, opts ...grpc.CallOption) (M, error) {
	req := REQ(new(REQT))
	req.SetId(id)

	resp, err := get(ctx, req, opts...)
	if err != nil {
		return *new(M), err
	}

	return AnyTo[M](resp.GetItem())
}

func List[M proto.Message, REQT any, REQ id[REQT], RESP items](list func(context.Context, REQ, ...grpc.CallOption) (RESP, error), ctx context.Context, id string, opts ...grpc.CallOption) ([]M, error) {
	req := REQ(new(REQT))
	req.SetId(id)

	resp, err := list(ctx, req, opts...)
	if err != nil {
		return nil, err
	}

	var ms []M
	for _, item := range resp.GetItems() {
		m, err := AnyTo[M](item)
		if err != nil {
			return nil, err
		}

		ms = append(ms, m)
	}

	return ms, nil
}

// ListByType filters parent list responses to the concrete protobuf type M.
// It still fails if a matching Any payload cannot be decoded.
func ListByType[M proto.Message, REQT any, REQ id[REQT], RESP items](list func(context.Context, REQ, ...grpc.CallOption) (RESP, error), ctx context.Context, id string, opts ...grpc.CallOption) ([]M, error) {
	req := REQ(new(REQT))
	req.SetId(id)

	resp, err := list(ctx, req, opts...)
	if err != nil {
		return nil, err
	}

	typeURL, err := typeURLFor[M]()
	if err != nil {
		return nil, err
	}

	var ms []M
	for _, item := range resp.GetItems() {
		if item.GetTypeUrl() != typeURL {
			continue
		}

		m, err := AnyTo[M](item)
		if err != nil {
			return nil, err
		}

		ms = append(ms, m)
	}

	return ms, nil
}

func typeURLFor[M proto.Message]() (string, error) {
	msg, err := newProtoMessage[M]()
	if err != nil {
		return "", err
	}
	return "type.googleapis.com/" + string(msg.ProtoReflect().Descriptor().FullName()), nil
}

func newProtoMessage[M proto.Message]() (M, error) {
	var zero M
	t := reflect.TypeOf(zero)
	if t == nil {
		return zero, fmt.Errorf("proto message type has no concrete type")
	}
	if t.Kind() != reflect.Pointer {
		return zero, fmt.Errorf("proto message type %T must be a pointer", zero)
	}
	msg, ok := reflect.New(t.Elem()).Interface().(M)
	if !ok {
		return zero, fmt.Errorf("proto message type %T cannot be constructed", zero)
	}
	return msg, nil
}

func AnyTo[M proto.Message](o *anypb.Any) (M, error) {
	m, err := o.UnmarshalNew()
	if err != nil {
		return *new(M), err
	}

	return To[M](m)
}

func To[M proto.Message](m any) (M, error) {
	if m, ok := m.(M); ok {
		return m, nil
	}

	return *new(M), status.Error(codes.InvalidArgument, "type mismatch")
}
