package karpenter

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"os/exec"
	"strings"
	"text/template"

	"github.com/Azure/azure-sdk-for-go/sdk/azidentity"
	"github.com/spf13/cobra"

	"github.com/Azure/aks-flex/cli/internal/config/configcmd"
	"github.com/Azure/aks-flex/plugin/pkg/util/az"
	"github.com/Azure/aks-flex/plugin/pkg/util/ssh"
)

var valuesTemplate = template.Must(template.New("karpenter-values").Parse(`# Karpenter Helm values — generated by: aks-flex-cli config karpenter helm
# Deploy with:
#   helm upgrade --install karpenter charts/karpenter \
#     --namespace karpenter --create-namespace \
#     --values karpenter_values.yaml
#
# To embed Nebius credentials and have the chart create the Secret automatically:
#   aks-flex-cli config karpenter helm --nebius-credentials-file <path>

settings:
  clusterName: "{{ .ClusterName }}"
  clusterEndpoint: "{{ .ClusterEndpoint }}"

logLevel: debug
replicas: 1

serviceAccount:
  annotations:
    azure.workload.identity/client-id: "{{ .AzureClientID }}"

podLabels:
  azure.workload.identity/use: "true"

controller:
  nebiusCredentials:
{{- if .NebiusCredentialsJSON }}
    enabled: true
    credentialsJSON: {{ .NebiusCredentialsJSON }}
{{- else }}
    enabled: false
{{- end }}
  image:
    digest: ""
{{- if .ImageRepository }}
    repository: "{{ .ImageRepository }}"
{{- end }}
{{- if .ImageTag }}
    tag: "{{ .ImageTag }}"
{{- end }}
  env:
    - name: ARM_CLOUD
      value: "{{ .ARMCloud }}"
    - name: LOCATION
      value: "{{ .Location }}"
    - name: ARM_RESOURCE_GROUP
      value: "{{ .ARMResourceGroup }}"
    - name: AZURE_TENANT_ID
      value: "{{ .AzureTenantID }}"
    - name: AZURE_CLIENT_ID
      value: "{{ .AzureClientID }}"
    - name: AZURE_SUBSCRIPTION_ID
      value: "{{ .AzureSubscriptionID }}"
    - name: AZURE_NODE_RESOURCE_GROUP
      value: "{{ .NodeResourceGroup }}"
    - name: SSH_PUBLIC_KEY
      value: "{{ .SSHPublicKey }}"
    - name: VNET_SUBNET_ID
      value: "{{ .VNETSubnetID }}"
    - name: KUBELET_BOOTSTRAP_TOKEN
      value: "{{ .KubeletBootstrapToken }}"
    - name: DISABLE_LEADER_ELECTION
      value: "false"
`))

type helmContext struct {
	ClusterName           string
	ClusterEndpoint       string
	ARMCloud              string
	Location              string
	ARMResourceGroup      string
	AzureTenantID         string
	AzureClientID         string
	AzureSubscriptionID   string
	NodeResourceGroup     string
	SSHPublicKey          string
	VNETSubnetID          string
	KubeletBootstrapToken string
	ImageRepository       string
	ImageTag              string
	NebiusCredentialsJSON string // JSON-encoded string, valid YAML scalar
}

func (hc *helmContext) resolve(ctx context.Context) {
	cfg := configcmd.DefaultConfig()

	// Values sourced from the shared config.
	clusterName := ""
	location := ""
	resourceGroup := ""
	subscriptionID := ""
	if cfg != nil {
		clusterName = cfg.ClusterName
		location = cfg.Location
		resourceGroup = cfg.ResourceGroupName
		subscriptionID = cfg.SubscriptionID
	}

	hc.ClusterName = configcmd.OrPlaceholder(clusterName)
	hc.Location = configcmd.OrPlaceholder(location)
	hc.ARMResourceGroup = configcmd.OrPlaceholder(resourceGroup)
	hc.AzureSubscriptionID = configcmd.OrPlaceholder(subscriptionID)
	hc.ARMCloud = "AzurePublicCloud"

	// Tenant ID — resolve via az CLI.
	if tenantID, err := execOutput(ctx, "az", "account", "show", "--query", "tenantId", "-o", "tsv"); err == nil {
		hc.AzureTenantID = tenantID
	} else {
		hc.AzureTenantID = configcmd.OrPlaceholder("")
	}

	hc.SSHPublicKey = "ssh-key-not-set"
	if flagLoadSSHKey {
		// asked to load ssh key from host — attempt to load the default SSH public key.
		if pubKey, err := ssh.PublicKey(); err == nil {
			hc.SSHPublicKey = strings.TrimSpace(string(pubKey))
		}
	}

	// Bootstrap token — resolve from DefaultKubeadmConfig.
	kubeadmCfg := configcmd.DefaultKubeadmConfig(ctx)
	hc.KubeletBootstrapToken = configcmd.OrPlaceholder(kubeadmCfg.GetToken())

	// Cluster endpoint, node resource group, and VNET subnet ID — resolve
	// from the Azure ManagedCluster resource.
	hc.ClusterEndpoint = configcmd.OrPlaceholder("")
	hc.NodeResourceGroup = configcmd.OrPlaceholder("")
	hc.VNETSubnetID = configcmd.OrPlaceholder("")

	// Karpenter managed identity client ID — resolve via az CLI.
	if clientID, err := execOutput(ctx, "az", "identity", "show",
		"--name", "karpenter-flex",
		"--resource-group", resourceGroup,
		"--query", "clientId", "-o", "tsv"); err == nil {
		hc.AzureClientID = clientID
	} else {
		hc.AzureClientID = configcmd.OrPlaceholder("")
	}

	if cfg == nil {
		return
	}

	credentials, err := azidentity.NewAzureCLICredential(nil)
	if err != nil {
		warn("could not obtain Azure credentials: %v", err)
		return
	}

	mc, err := az.ManagedCluster(ctx, credentials, cfg)
	if err != nil {
		warn("could not retrieve managed cluster: %v", err)
		return
	}

	if mc.Properties != nil {
		if mc.Properties.Fqdn != nil {
			hc.ClusterEndpoint = "https://" + *mc.Properties.Fqdn + ":443"
		}
		if mc.Properties.NodeResourceGroup != nil {
			hc.NodeResourceGroup = *mc.Properties.NodeResourceGroup
		}
		if len(mc.Properties.AgentPoolProfiles) > 0 && mc.Properties.AgentPoolProfiles[0].VnetSubnetID != nil {
			hc.VNETSubnetID = *mc.Properties.AgentPoolProfiles[0].VnetSubnetID
		}
	}
}

func execOutput(ctx context.Context, name string, args ...string) (string, error) {
	cmd := exec.CommandContext(ctx, name, args...) // #nosec G204
	out, err := cmd.Output()
	if err != nil {
		return "", err
	}
	return strings.TrimSpace(string(out)), nil
}

func warn(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "Warning: "+format+"\n", args...)
	fmt.Fprintln(os.Stderr, "Using placeholder values — edit the output before applying.")
}

// Command is the "config karpenter" parent command.
var Command = &cobra.Command{
	Use:   "karpenter",
	Short: "Karpenter-provider-flex configuration commands",
}

var helmCmd = &cobra.Command{
	Use:   "helm",
	Short: "Generate karpenter_values.yaml for helm install/upgrade",
	Long: `Generate a karpenter_values.yaml file for deploying karpenter.

Values are resolved from the shared config (environment variables) and the
Azure ManagedCluster resource. Any value that cannot be resolved is replaced
with a placeholder that must be edited before running the command.

After generation, deploy with:
  helm upgrade --install karpenter charts/karpenter \
    --namespace karpenter --create-namespace \
    --values karpenter_values.yaml`,
	Args: cobra.NoArgs,
	RunE: func(cmd *cobra.Command, _ []string) error {
		return runHelm(cmd.Context(), cmd.OutOrStdout(), cmd.ErrOrStderr())
	},
}

var (
	flagImage                 string
	flagLoadSSHKey            bool
	flagSSHPublicKeyFile      string
	flagOutput                string
	flagNebiusCredentialsFile string
)

func init() {
	helmCmd.Flags().StringVar(&flagImage, "image", "", "override controller image (e.g. myregistry.io/karpenter:v0.1.0)")
	helmCmd.Flags().BoolVar(&flagLoadSSHKey, "load-ssh-key", false, "whether to attempt to load the SSH public key from the default host path")
	helmCmd.Flags().StringVar(&flagSSHPublicKeyFile, "ssh-public-key-file", "", "path to SSH public key file to embed as SSH_PUBLIC_KEY")
	helmCmd.Flags().StringVar(&flagOutput, "output", "karpenter_values.yaml", "path to write the generated values file")
	helmCmd.Flags().StringVar(&flagNebiusCredentialsFile, "nebius-credentials-file", "", "path to Nebius credentials JSON; when set the chart creates the nebius-credentials Secret automatically")
	Command.AddCommand(helmCmd)
}

func runHelm(ctx context.Context, out io.Writer, errOut io.Writer) error {
	hc := &helmContext{}
	hc.resolve(ctx)

	// --ssh-public-key-file overrides the value set by resolve() / --load-ssh-key.
	if flagSSHPublicKeyFile != "" {
		data, err := os.ReadFile(flagSSHPublicKeyFile) // #nosec G304
		if err != nil {
			return fmt.Errorf("reading ssh public key file: %w", err)
		}
		hc.SSHPublicKey = strings.TrimSpace(string(data))
	}

	// Parse --image flag into repository and tag if provided.
	if flagImage != "" {
		if repo, tag, ok := strings.Cut(flagImage, ":"); ok {
			hc.ImageRepository = repo
			hc.ImageTag = tag
		} else {
			hc.ImageRepository = flagImage
		}
	}

	// Read and embed Nebius credentials so the helm command stays simple.
	if flagNebiusCredentialsFile != "" {
		data, err := os.ReadFile(flagNebiusCredentialsFile) // #nosec G304
		if err != nil {
			return fmt.Errorf("reading nebius credentials file: %w", err)
		}
		// JSON-encode the string so it is a valid single-line YAML scalar.
		encoded, err := json.Marshal(strings.TrimSpace(string(data)))
		if err != nil {
			return fmt.Errorf("encoding nebius credentials: %w", err)
		}
		hc.NebiusCredentialsJSON = string(encoded)
	}

	var buf bytes.Buffer
	if err := valuesTemplate.Execute(&buf, hc); err != nil {
		return fmt.Errorf("rendering values file: %w", err)
	}

	if err := os.WriteFile(flagOutput, buf.Bytes(), 0o644); err != nil {
		return fmt.Errorf("writing %s: %w", flagOutput, err)
	}

	// Collect write errors from sequential output calls.
	var writeErr error
	write := func(w io.Writer, format string, args ...any) {
		if writeErr != nil {
			return
		}
		_, writeErr = fmt.Fprintf(w, format, args...)
	}

	write(errOut, "Written to %s\n\n", flagOutput)
	write(out, "helm upgrade --install karpenter charts/karpenter \\\n")
	write(out, "  --namespace karpenter --create-namespace \\\n")
	write(out, "  --values %s\n", flagOutput)
	return writeErr
}
