//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/awslabs/operatorpkg/status"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureFlexImageReference) DeepCopyInto(out *AzureFlexImageReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureFlexImageReference.
func (in *AzureFlexImageReference) DeepCopy() *AzureFlexImageReference {
	if in == nil {
		return nil
	}
	out := new(AzureFlexImageReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureFlexNodeClass) DeepCopyInto(out *AzureFlexNodeClass) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureFlexNodeClass.
func (in *AzureFlexNodeClass) DeepCopy() *AzureFlexNodeClass {
	if in == nil {
		return nil
	}
	out := new(AzureFlexNodeClass)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AzureFlexNodeClass) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureFlexNodeClassList) DeepCopyInto(out *AzureFlexNodeClassList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AzureFlexNodeClass, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureFlexNodeClassList.
func (in *AzureFlexNodeClassList) DeepCopy() *AzureFlexNodeClassList {
	if in == nil {
		return nil
	}
	out := new(AzureFlexNodeClassList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AzureFlexNodeClassList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureFlexNodeClassSpec) DeepCopyInto(out *AzureFlexNodeClassSpec) {
	*out = *in
	if in.ImageReference != nil {
		in, out := &in.ImageReference, &out.ImageReference
		*out = new(AzureFlexImageReference)
		**out = **in
	}
	if in.ImageID != nil {
		in, out := &in.ImageID, &out.ImageID
		*out = new(string)
		**out = **in
	}
	if in.SecurityType != nil {
		in, out := &in.SecurityType, &out.SecurityType
		*out = new(string)
		**out = **in
	}
	if in.OSDiskSizeGB != nil {
		in, out := &in.OSDiskSizeGB, &out.OSDiskSizeGB
		*out = new(int32)
		**out = **in
	}
	if in.SSHPublicKeys != nil {
		in, out := &in.SSHPublicKeys, &out.SSHPublicKeys
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AllocateNodePublicIP != nil {
		in, out := &in.AllocateNodePublicIP, &out.AllocateNodePublicIP
		*out = new(bool)
		**out = **in
	}
	if in.MaxPodsPerNode != nil {
		in, out := &in.MaxPodsPerNode, &out.MaxPodsPerNode
		*out = new(int32)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureFlexNodeClassSpec.
func (in *AzureFlexNodeClassSpec) DeepCopy() *AzureFlexNodeClassSpec {
	if in == nil {
		return nil
	}
	out := new(AzureFlexNodeClassSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureFlexNodeClassStatus) DeepCopyInto(out *AzureFlexNodeClassStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]status.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureFlexNodeClassStatus.
func (in *AzureFlexNodeClassStatus) DeepCopy() *AzureFlexNodeClassStatus {
	if in == nil {
		return nil
	}
	out := new(AzureFlexNodeClassStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NebiusNodeClass) DeepCopyInto(out *NebiusNodeClass) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NebiusNodeClass.
func (in *NebiusNodeClass) DeepCopy() *NebiusNodeClass {
	if in == nil {
		return nil
	}
	out := new(NebiusNodeClass)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NebiusNodeClass) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NebiusNodeClassList) DeepCopyInto(out *NebiusNodeClassList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NebiusNodeClass, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NebiusNodeClassList.
func (in *NebiusNodeClassList) DeepCopy() *NebiusNodeClassList {
	if in == nil {
		return nil
	}
	out := new(NebiusNodeClassList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NebiusNodeClassList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NebiusNodeClassSpec) DeepCopyInto(out *NebiusNodeClassSpec) {
	*out = *in
	if in.OSDiskSizeGB != nil {
		in, out := &in.OSDiskSizeGB, &out.OSDiskSizeGB
		*out = new(int32)
		**out = **in
	}
	if in.OSDiskImageFamily != nil {
		in, out := &in.OSDiskImageFamily, &out.OSDiskImageFamily
		*out = new(string)
		**out = **in
	}
	if in.AllocateNodePublicIP != nil {
		in, out := &in.AllocateNodePublicIP, &out.AllocateNodePublicIP
		*out = new(bool)
		**out = **in
	}
	if in.WireguardPeerCIDR != nil {
		in, out := &in.WireguardPeerCIDR, &out.WireguardPeerCIDR
		*out = new(string)
		**out = **in
	}
	if in.MaxPodsPerNode != nil {
		in, out := &in.MaxPodsPerNode, &out.MaxPodsPerNode
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NebiusNodeClassSpec.
func (in *NebiusNodeClassSpec) DeepCopy() *NebiusNodeClassSpec {
	if in == nil {
		return nil
	}
	out := new(NebiusNodeClassSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NebiusNodeClassStatus) DeepCopyInto(out *NebiusNodeClassStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]status.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NebiusNodeClassStatus.
func (in *NebiusNodeClassStatus) DeepCopy() *NebiusNodeClassStatus {
	if in == nil {
		return nil
	}
	out := new(NebiusNodeClassStatus)
	in.DeepCopyInto(out)
	return out
}
